export const ROUTES_ENUM = {
  ROOT: "/",
  LOGIN: "/login",
  RES_PASSWORD: "/resetpassword",
  PASS_CHANGE: "/passwordchange",
  OPT: "/otp",
  CRE_PASSWORD: "/createpassword",
  DASHBOARD: "/dashboard",
  PROJECTS: "/projects",
  TRADES: "/trades",
  BIDS: "/bids",
  BID_DETAILS: "/bid-details",
  BID_COMPARISON: "/bid-comparison",
  FILES: "/files",
  TEAMS: "/teams",
};
